version: "3.3"

services:
  mysql:
    container_name: mysql
    build: ../mysql57/
    restart: unless-stopped
    tty: true
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD:true
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    command: mysqld --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
      - ../mysql57/my.cnf:/etc/mysql/my.cnf
    networks:
      - backend
  phpmyadmin:
    container_name: phpmyadmin
    build: ../phpmyadmin/
    restart: unless-stopped
    environment:
      - PMA_HOST:mysql
    ports:
      - 8857:80
    depends_on:
      - mysql
    networks:
      - backend
  memcached:
    container_name: memcached
    image: memcached:1.5.19
    restart: unless-stopped
    networks:
      - backend
  redis:
    container_name: redis
    image: redis:latest
    volumes:
      - db-redis:/data
    ports:
      - 6379:6379
    networks:
      - backend
  jsbackend:
    container_name: jsbackend
    image: shaunlin064/php5.6_apache:latest
    restart: unless-stopped
    ports:
      - 8081:80
    volumes:
      - "${STORAGE_PATH}:/var/www/html"
      - js-logs:/var/log/apache2
      - ../js_erp/php.ini:/usr/local/etc/php/php.ini
      - ../js_erp/000-default.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - mysql
      - memcached
    networks:
      - backend
  dac:
    container_name: dac
    build: ../dataanalysiscontrol/
    restart: unless-stopped
    volumes:
      - "${STORAGE_PATH}:/var/project"
      - dac-logs:/var/log/apache2
    working_dir: /var/project/dataanalysiscontrol
    depends_on:
      - mysql
      - memcached
      - jsbackend
    networks:
      - backend
  media_effect:
    container_name: media_effect
    build: ../media_effect/
    restart: unless-stopped
    volumes:
      - "${STORAGE_PATH}:/var/project"
    working_dir: /var/project/media_effect
    depends_on:
      - mysql
      - memcached
    networks:
      - backend
  invoice:
    container_name: invoice
    image: shaunlin064/php71_fpm:latest
    restart: unless-stopped
    volumes:
      - "${STORAGE_PATH}:/var/project"
    working_dir: /var/project/invoice
    depends_on:
      - mysql
      - memcached
    networks:
      - backend
  nginx:
    container_name: nginx
    build: ../nginx/
    restart: unless-stopped
    ports:
      - 8082:80
      - 8083:81
      - 8084:82
    links:
      - dac:phpfpm
    volumes:
      - "${STORAGE_PATH}:/var/project"
      - ../nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - backend
networks:
  backend:
volumes:
  db-data:
  js-logs:
  dac-logs:
  db-redis: