version: "3.3"

services:
  mysql:
    container_name: mysql
    image: shaunlin064/mysql57:latest
    restart: unless-stopped
    tty: true
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD:true
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=Asia/Taipei
    command: mysqld --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
      - ../mysql57/my.cnf:/etc/mysql/my.cnf
    networks:
      - backend
  mysql56:
    container_name: mysql56
    image: mysql:5.6
    restart: unless-stopped
    tty: true
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD:true
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=Asia/Taipei
    ports:
      - 3307:3306
    volumes:
      - db-data-mysql56:/var/lib/mysql
    networks:
      - backend
  phpmyadmin:
    container_name: phpmyadmin
    image: shaunlin064/phpmyadmin:latest
    restart: unless-stopped
    environment:
      - PMA_HOST:mysql
    links:
      - mysql56:mysql
    ports:
      - 8857:80
    depends_on:
      - mysql56
    networks:
      - backend
  memcached:
    container_name: memcached
    image: memcached:1.5.19
    restart: unless-stopped
    networks:
      - backend
  php56:
    container_name: php56
    image: shaunlin064/php56_fpm:latest
    restart: unless-stopped
    volumes:
      - "${STORAGE_PATH}:/var/project"
      - ./config/php/56/php.ini:/usr/local/etc/php/php.ini
    working_dir: /var/project/
    depends_on:
      - memcached
    networks:
      - backend
#  python3:
#    container_name: python3
#    build: ../python/
#    restart: unless-stopped
#    volumes:
#      - "${STORAGE_PATH}:/var/project"
#    command: >
#          bash -c "tail -F /var/project/test.log"
#    working_dir: /var/project/
#    networks:
#      - backend
  php74:
    container_name: php74
    image: shaunlin064/php74_fpm:latest
    restart: unless-stopped
#    environment:
#      XDEBUG_CONFIG: remote_host=${XDEBUG_REMOTE_HOST:-host.docker.internal}
    volumes:
      - "${STORAGE_PATH}:/var/project"
      - ./config/cron/schedule-cron:/etc/cron.d/schedule-cron
#      - ./config/supervisor/laravel-worker.conf:/etc/supervisor/conf.d/laravel-worker.conf
      - ./config/php/74/php.ini:/usr/local/etc/php/php.ini
#      - ./config/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    command: >
      bash -c "chmod 0777 /etc/cron.d/schedule-cron
      && crontab /etc/cron.d/schedule-cron
      && service cron restart
      && php-fpm
      && supervisord"
    working_dir: /var/project/
    depends_on:
      - memcached
    networks:
      - backend
  nginx:
    container_name: nginx
    image: shaunlin064/nginx:latest
    restart: unless-stopped
    ports:
      - 127.0.0.2:80:80 #jserp
      - 127.0.0.3:80:81 #dac
#      - 127.0.0.4:80:82 #media
#      - 127.0.0.4:80:83 #invoice
      - 127.0.0.5:80:84 #signing
#      - 127.0.0.6:80:85 #customer
      - 127.0.0.7:80:98 #project_start
    links:
      - php56:phpfpm
      - php74:phpfpm
    volumes:
      - "${STORAGE_PATH}:/var/project"
      - ../nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    user: root:www-data
    depends_on:
      - php56
      - php74
    networks:
      - backend
networks:
  backend:
volumes:
  db-data:
  db-data-mysql56: