version: "3.3"

services:
  mysql:
    container_name: mysql
    image: shaunlin064/mysql57:latest
    restart: unless-stopped
    tty: true
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD:true
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    command: mysqld --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
      - ../mysql57/my.cnf:/etc/mysql/my.cnf
    networks:
      - backend
  phpmyadmin:
    container_name: phpmyadmin
    image: shaunlin064/phpmyadmin:latest
    restart: unless-stopped
    environment:
      - PMA_HOST:mysql
    ports:
      - 8857:80
    depends_on:
      - mysql
    networks:
      - backend
  memcached:
    container_name: memcached
    image: memcached:1.5.19
    restart: unless-stopped
    networks:
      - backend
  redis:
    container_name: redis
    image: redis:latest
    restart: unless-stopped
    volumes:
      - db-redis:/data
    ports:
      - 6379:6379
    networks:
      - backend
  php56:
    container_name: php56
    image: shaunlin064/php56_fpm:latest
    restart: unless-stopped
    volumes:
      - "${STORAGE_PATH}:/var/project"
    working_dir: /var/project/
    depends_on:
      - mysql
      - memcached
    networks:
      - backend
  php71:
    container_name: php71
    image: shaunlin064/php71_fpm:latest
    restart: unless-stopped
    volumes:
      - "${STORAGE_PATH}:/var/project"
    working_dir: /var/project/
    depends_on:
      - mysql
      - memcached
    networks:
      - backend
  php73:
    container_name: php73
    image: shaunlin064/laravel_php73_fpm:latest
    restart: unless-stopped
    volumes:
      - "${STORAGE_PATH}:/var/project"
    working_dir: /var/project/
    depends_on:
      - mysql
      - memcached
    networks:
      - backend
  php74:
    container_name: php74
    image: shaunlin064/php74_fpm:latest
    restart: unless-stopped
    volumes:
      - "${STORAGE_PATH}:/var/project"
    working_dir: /var/project/
    depends_on:
      - mysql
      - memcached
    networks:
      - backend
  nginx:
    container_name: nginx
    image: shaunlin064/nginx:latest
    restart: unless-stopped
    ports:
      - 127.0.0.2:80:80 #jserp
      - 127.0.0.3:80:81 #dac
      - 127.0.0.4:80:82 #media
      - 127.0.0.4:80:83 #invoice
      - 127.0.0.5:80:84 #signing
    links:
      - php56:phpfpm
      - php71:phpfpm
      - php73:phpfpm
      - php74:phpfpm
    volumes:
      - "${STORAGE_PATH}:/var/project"
      - ../nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php56
      - php71
      - php73
      - php74
    networks:
      - backend
networks:
  backend:
volumes:
  db-data:
  db-redis: